"""Seed parking locations. Adapted from truckerpro-web seed_parking_data.py."""
import logging
from app.extensions import db
from app.models.location import ParkingLocation
from app.services.geo_service import slugify

logger = logging.getLogger(__name__)

SEED_LOCATIONS = [
    # ===== ONTARIO =====
    {
        'name': 'Flying J Travel Centre',
        'address': '5500 Hwy 401',
        'city': 'London',
        'province': 'ON',
        'latitude': 42.9578,
        'longitude': -81.3218,
        'location_type': 'truck_stop',
        'total_spots': 120,
        'bobtail_spots': 20,
        'trailer_spots': 80,
        'oversize_spots': 20,
        'daily_rate': 2500,
        'monthly_rate': 45000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "food_nearby", "restaurant_onsite", "fuel_nearby", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 401", "Hwy 402"],
    },
    {
        'name': 'Pilot Travel Center',
        'address': '3751 Hwy 401 E',
        'city': 'Woodstock',
        'province': 'ON',
        'latitude': 43.1167,
        'longitude': -80.7356,
        'location_type': 'truck_stop',
        'total_spots': 80,
        'bobtail_spots': 15,
        'trailer_spots': 55,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "restaurant_onsite", "fuel_nearby", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'ONroute West Lorne',
        'address': 'Hwy 401 Westbound',
        'city': 'West Lorne',
        'province': 'ON',
        'latitude': 42.7722,
        'longitude': -81.5139,
        'location_type': 'rest_area',
        'total_spots': 50,
        'trailer_spots': 40,
        'oversize_spots': 10,
        'amenities': ["restrooms", "food_nearby", "restaurant_onsite", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'ONroute Woodstock',
        'address': 'Hwy 401 Eastbound',
        'city': 'Woodstock',
        'province': 'ON',
        'latitude': 43.1200,
        'longitude': -80.7500,
        'location_type': 'rest_area',
        'total_spots': 45,
        'trailer_spots': 35,
        'oversize_spots': 10,
        'amenities': ["restrooms", "food_nearby", "restaurant_onsite", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'ONroute Trenton',
        'address': 'Hwy 401 Eastbound',
        'city': 'Trenton',
        'province': 'ON',
        'latitude': 44.0887,
        'longitude': -77.5711,
        'location_type': 'rest_area',
        'total_spots': 40,
        'trailer_spots': 30,
        'oversize_spots': 10,
        'amenities': ["restrooms", "food_nearby", "restaurant_onsite", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'Flying J Napanee',
        'address': '110 Jim Kimmett Blvd',
        'city': 'Napanee',
        'province': 'ON',
        'latitude': 44.2481,
        'longitude': -76.9497,
        'location_type': 'truck_stop',
        'total_spots': 100,
        'bobtail_spots': 15,
        'trailer_spots': 70,
        'oversize_spots': 15,
        'daily_rate': 2500,
        'monthly_rate': 45000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "restaurant_onsite", "fuel_nearby", "cat_scale", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'TA Express Belleville',
        'address': '200 Maitland Dr',
        'city': 'Belleville',
        'province': 'ON',
        'latitude': 44.1627,
        'longitude': -77.3832,
        'location_type': 'truck_stop',
        'total_spots': 60,
        'bobtail_spots': 10,
        'trailer_spots': 40,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "fuel_nearby", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'Husky Travel Centre',
        'address': '6484 Hwy 401',
        'city': 'Prescott',
        'province': 'ON',
        'latitude': 44.7141,
        'longitude': -75.5136,
        'location_type': 'truck_stop',
        'total_spots': 50,
        'bobtail_spots': 10,
        'trailer_spots': 30,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'ONroute Port Hope',
        'address': 'Hwy 401 Eastbound',
        'city': 'Port Hope',
        'province': 'ON',
        'latitude': 43.9500,
        'longitude': -78.3000,
        'location_type': 'rest_area',
        'total_spots': 45,
        'trailer_spots': 35,
        'oversize_spots': 10,
        'amenities': ["restrooms", "food_nearby", "restaurant_onsite", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'Petro-Canada Truck Stop',
        'address': '325 Hespeler Rd',
        'city': 'Cambridge',
        'province': 'ON',
        'latitude': 43.3976,
        'longitude': -80.3254,
        'location_type': 'truck_stop',
        'total_spots': 45,
        'bobtail_spots': 10,
        'trailer_spots': 30,
        'oversize_spots': 5,
        'daily_rate': 1800,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "paved", "lit_lot"],
        'nearby_highways': ["Hwy 401", "Hwy 8"],
    },
    {
        'name': 'Brampton Truck Yard',
        'address': '30 Bramwin Court',
        'city': 'Brampton',
        'province': 'ON',
        'latitude': 43.7315,
        'longitude': -79.7624,
        'location_type': 'private_yard',
        'total_spots': 60,
        'bobtail_spots': 10,
        'trailer_spots': 40,
        'oversize_spots': 10,
        'daily_rate': 3000,
        'weekly_rate': 15000,
        'monthly_rate': 50000,
        'amenities': ["security_camera", "24_7_access", "fenced", "gated", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 410", "Hwy 407"],
    },
    {
        'name': 'ONroute Bainsville',
        'address': 'Hwy 401 Westbound',
        'city': 'Bainsville',
        'province': 'ON',
        'latitude': 45.1883,
        'longitude': -74.4400,
        'location_type': 'rest_area',
        'total_spots': 35,
        'trailer_spots': 25,
        'oversize_spots': 10,
        'amenities': ["restrooms", "food_nearby", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'Mississauga Industrial Truck Parking',
        'address': '2225 Meadowpine Blvd',
        'city': 'Mississauga',
        'province': 'ON',
        'latitude': 43.6205,
        'longitude': -79.7151,
        'location_type': 'industrial_lot',
        'total_spots': 40,
        'trailer_spots': 30,
        'oversize_spots': 10,
        'daily_rate': 3500,
        'weekly_rate': 18000,
        'monthly_rate': 60000,
        'amenities': ["security_camera", "fenced", "gated", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 401", "Hwy 407", "Hwy 403"],
    },
    {
        'name': 'ONroute Ingleside',
        'address': 'Hwy 401 Eastbound',
        'city': 'Ingleside',
        'province': 'ON',
        'latitude': 44.9897,
        'longitude': -75.0158,
        'location_type': 'rest_area',
        'total_spots': 40,
        'trailer_spots': 30,
        'oversize_spots': 10,
        'amenities': ["restrooms", "food_nearby", "restaurant_onsite", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'Flying J Cornwall',
        'address': '3250 Brookdale Ave',
        'city': 'Cornwall',
        'province': 'ON',
        'latitude': 45.0198,
        'longitude': -74.7587,
        'location_type': 'truck_stop',
        'total_spots': 80,
        'bobtail_spots': 15,
        'trailer_spots': 50,
        'oversize_spots': 15,
        'daily_rate': 2500,
        'monthly_rate': 42000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "restaurant_onsite", "fuel_nearby", "cat_scale", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'ONroute Napanee',
        'address': 'Hwy 401 Westbound',
        'city': 'Napanee',
        'province': 'ON',
        'latitude': 44.2500,
        'longitude': -76.9000,
        'location_type': 'rest_area',
        'total_spots': 40,
        'trailer_spots': 30,
        'oversize_spots': 10,
        'amenities': ["restrooms", "food_nearby", "restaurant_onsite", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'Thunder Bay Truck Terminal',
        'address': '555 Harbour Expressway',
        'city': 'Thunder Bay',
        'province': 'ON',
        'latitude': 48.3809,
        'longitude': -89.2477,
        'location_type': 'truck_stop',
        'total_spots': 35,
        'bobtail_spots': 10,
        'trailer_spots': 20,
        'oversize_spots': 5,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada"],
    },
    {
        'name': 'Petro-Pass Truck Stop',
        'address': '7500 Hwy 400',
        'city': 'Barrie',
        'province': 'ON',
        'latitude': 44.3894,
        'longitude': -79.6903,
        'location_type': 'truck_stop',
        'total_spots': 55,
        'bobtail_spots': 10,
        'trailer_spots': 35,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 400"],
    },
    # ===== MANITOBA =====
    {
        'name': 'Flying J Travel Centre Winnipeg',
        'address': '3760 Portage Ave',
        'city': 'Winnipeg',
        'province': 'MB',
        'latitude': 49.8844,
        'longitude': -97.2780,
        'location_type': 'truck_stop',
        'total_spots': 150,
        'bobtail_spots': 25,
        'trailer_spots': 100,
        'oversize_spots': 25,
        'lcv_capable': True,
        'daily_rate': 2000,
        'monthly_rate': 35000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "restaurant_onsite", "fuel_nearby", "cat_scale", "block_heater_plugin", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    {
        'name': 'Pilot Travel Center',
        'address': '2020 Voyageur Rd',
        'city': 'Winnipeg',
        'province': 'MB',
        'latitude': 49.8500,
        'longitude': -97.0600,
        'location_type': 'truck_stop',
        'total_spots': 44,
        'bobtail_spots': 10,
        'trailer_spots': 30,
        'oversize_spots': 4,
        'daily_rate': 1800,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "fuel_nearby", "lit_lot", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    {
        'name': 'Husky Travel Centre Brandon',
        'address': '1 Victoria Ave E',
        'city': 'Brandon',
        'province': 'MB',
        'latitude': 49.8418,
        'longitude': -99.9389,
        'location_type': 'truck_stop',
        'total_spots': 40,
        'bobtail_spots': 8,
        'trailer_spots': 25,
        'oversize_spots': 7,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    {
        'name': 'Petro-Canada Whiteshell',
        'address': 'Trans-Canada Hwy 1',
        'city': 'Whiteshell',
        'province': 'MB',
        'latitude': 49.9500,
        'longitude': -95.6800,
        'location_type': 'truck_stop',
        'total_spots': 25,
        'trailer_spots': 20,
        'oversize_spots': 5,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "gravel"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    {
        'name': 'Portage la Prairie Truck Stop',
        'address': '2700 Saskatchewan Ave W',
        'city': 'Portage la Prairie',
        'province': 'MB',
        'latitude': 49.9728,
        'longitude': -98.3167,
        'location_type': 'truck_stop',
        'total_spots': 35,
        'bobtail_spots': 5,
        'trailer_spots': 25,
        'oversize_spots': 5,
        'lcv_capable': True,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 1", "Hwy 16"],
    },
    {
        'name': 'Winnipeg CentrePort Truck Parking',
        'address': '1000 CentrePort Canada Way',
        'city': 'Winnipeg',
        'province': 'MB',
        'latitude': 49.9200,
        'longitude': -97.2900,
        'location_type': 'industrial_lot',
        'total_spots': 80,
        'trailer_spots': 60,
        'oversize_spots': 20,
        'lcv_capable': True,
        'daily_rate': 2500,
        'weekly_rate': 12000,
        'monthly_rate': 40000,
        'amenities': ["security_camera", "24_7_access", "fenced", "gated", "lit_lot", "paved", "snow_removal", "block_heater_plugin"],
        'nearby_highways': ["Trans-Canada", "Hwy 1", "Hwy 101"],
    },
    # ===== ALBERTA =====
    {
        'name': 'Flying J Calgary South',
        'address': '200 Aero Dr SE',
        'city': 'Calgary',
        'province': 'AB',
        'latitude': 50.8779,
        'longitude': -113.9540,
        'location_type': 'truck_stop',
        'total_spots': 130,
        'bobtail_spots': 20,
        'trailer_spots': 90,
        'oversize_spots': 20,
        'lcv_capable': True,
        'daily_rate': 2500,
        'monthly_rate': 45000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "restaurant_onsite", "fuel_nearby", "cat_scale", "block_heater_plugin", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["QE2", "Hwy 2"],
    },
    {
        'name': 'Husky Travel Centre Red Deer',
        'address': '7101 50 Ave',
        'city': 'Red Deer',
        'province': 'AB',
        'latitude': 52.2681,
        'longitude': -113.8112,
        'location_type': 'truck_stop',
        'total_spots': 60,
        'bobtail_spots': 10,
        'trailer_spots': 40,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["QE2", "Hwy 2"],
    },
    {
        'name': 'Flying J Edmonton South',
        'address': '3804 Calgary Trail NW',
        'city': 'Edmonton',
        'province': 'AB',
        'latitude': 53.4640,
        'longitude': -113.4937,
        'location_type': 'truck_stop',
        'total_spots': 120,
        'bobtail_spots': 20,
        'trailer_spots': 80,
        'oversize_spots': 20,
        'lcv_capable': True,
        'daily_rate': 2500,
        'monthly_rate': 45000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "restaurant_onsite", "fuel_nearby", "cat_scale", "block_heater_plugin", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["QE2", "Hwy 2"],
    },
    {
        'name': 'Pilot Flying J Airdrie',
        'address': '276 East Lake Blvd NE',
        'city': 'Airdrie',
        'province': 'AB',
        'latitude': 51.2917,
        'longitude': -114.0144,
        'location_type': 'truck_stop',
        'total_spots': 70,
        'bobtail_spots': 10,
        'trailer_spots': 50,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "fuel_nearby", "cat_scale", "block_heater_plugin", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["QE2", "Hwy 2"],
    },
    {
        'name': 'Gasoline Alley Truck Stop',
        'address': '6430 Johnstone Dr',
        'city': 'Red Deer',
        'province': 'AB',
        'latitude': 52.2100,
        'longitude': -113.8000,
        'location_type': 'truck_stop',
        'total_spots': 50,
        'bobtail_spots': 10,
        'trailer_spots': 35,
        'oversize_spots': 5,
        'daily_rate': 1800,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "truck_wash", "block_heater_plugin", "paved"],
        'nearby_highways': ["QE2", "Hwy 2"],
    },
    {
        'name': 'Nisku Truck Terminal',
        'address': '1200 1st Ave',
        'city': 'Nisku',
        'province': 'AB',
        'latitude': 53.3300,
        'longitude': -113.5200,
        'location_type': 'industrial_lot',
        'total_spots': 100,
        'trailer_spots': 70,
        'oversize_spots': 30,
        'lcv_capable': True,
        'daily_rate': 3000,
        'weekly_rate': 15000,
        'monthly_rate': 50000,
        'amenities': ["security_camera", "24_7_access", "fenced", "gated", "lit_lot", "paved", "snow_removal", "block_heater_plugin"],
        'nearby_highways': ["QE2", "Hwy 2"],
    },
    {
        'name': 'Petro-Canada Lethbridge',
        'address': '1720 Mayor Magrath Dr S',
        'city': 'Lethbridge',
        'province': 'AB',
        'latitude': 49.6818,
        'longitude': -112.8285,
        'location_type': 'truck_stop',
        'total_spots': 30,
        'bobtail_spots': 5,
        'trailer_spots': 20,
        'oversize_spots': 5,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "paved"],
        'nearby_highways': ["Hwy 3", "Hwy 4"],
    },
    {
        'name': 'Medicine Hat Truck Stop',
        'address': '935 Trans-Canada Way SE',
        'city': 'Medicine Hat',
        'province': 'AB',
        'latitude': 50.0405,
        'longitude': -110.6764,
        'location_type': 'truck_stop',
        'total_spots': 40,
        'bobtail_spots': 8,
        'trailer_spots': 25,
        'oversize_spots': 7,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    # ===== BRITISH COLUMBIA =====
    {
        'name': 'Flying J Kamloops',
        'address': '1520 Hugh Allan Dr',
        'city': 'Kamloops',
        'province': 'BC',
        'latitude': 50.7120,
        'longitude': -120.3192,
        'location_type': 'truck_stop',
        'total_spots': 80,
        'bobtail_spots': 15,
        'trailer_spots': 50,
        'oversize_spots': 15,
        'daily_rate': 2500,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "restaurant_onsite", "fuel_nearby", "cat_scale", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 1", "Hwy 5", "Hwy 97"],
    },
    {
        'name': 'Husky Travel Centre Hope',
        'address': '795 Old Hope Princeton Way',
        'city': 'Hope',
        'province': 'BC',
        'latitude': 49.3810,
        'longitude': -121.4419,
        'location_type': 'truck_stop',
        'total_spots': 50,
        'bobtail_spots': 10,
        'trailer_spots': 30,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 1", "Hwy 3", "Hwy 5"],
    },
    {
        'name': 'Petro-Canada Merritt',
        'address': '2900 Voght St',
        'city': 'Merritt',
        'province': 'BC',
        'latitude': 50.1055,
        'longitude': -120.7862,
        'location_type': 'truck_stop',
        'total_spots': 35,
        'bobtail_spots': 5,
        'trailer_spots': 25,
        'oversize_spots': 5,
        'daily_rate': 1800,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "paved"],
        'nearby_highways': ["Hwy 5", "Hwy 97C"],
    },
    {
        'name': 'Surrey Industrial Truck Parking',
        'address': '12880 86th Ave',
        'city': 'Surrey',
        'province': 'BC',
        'latitude': 49.1560,
        'longitude': -122.8517,
        'location_type': 'industrial_lot',
        'total_spots': 50,
        'trailer_spots': 35,
        'oversize_spots': 15,
        'daily_rate': 4000,
        'weekly_rate': 20000,
        'monthly_rate': 65000,
        'amenities': ["security_camera", "24_7_access", "fenced", "gated", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 1", "Hwy 99"],
    },
    {
        'name': 'Prince George Truck Stop',
        'address': '6800 Hwy 97 S',
        'city': 'Prince George',
        'province': 'BC',
        'latitude': 53.8677,
        'longitude': -122.7575,
        'location_type': 'truck_stop',
        'total_spots': 45,
        'bobtail_spots': 10,
        'trailer_spots': 30,
        'oversize_spots': 5,
        'daily_rate': 1800,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 97", "Hwy 16"],
    },
    {
        'name': 'Abbotsford Truck Terminal',
        'address': '34050 South Fraser Way',
        'city': 'Abbotsford',
        'province': 'BC',
        'latitude': 49.0504,
        'longitude': -122.3045,
        'location_type': 'truck_stop',
        'total_spots': 55,
        'bobtail_spots': 10,
        'trailer_spots': 35,
        'oversize_spots': 10,
        'daily_rate': 2500,
        'amenities': ["security_camera", "24_7_access", "restrooms", "fuel_nearby", "lit_lot", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    {
        'name': 'Revelstoke Rest Area',
        'address': 'Trans-Canada Hwy 1',
        'city': 'Revelstoke',
        'province': 'BC',
        'latitude': 51.0000,
        'longitude': -118.1957,
        'location_type': 'rest_area',
        'total_spots': 20,
        'trailer_spots': 15,
        'oversize_spots': 5,
        'amenities': ["restrooms", "lit_lot", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    # ===== SASKATCHEWAN =====
    {
        'name': 'Flying J Regina',
        'address': '1400 E Victoria Ave',
        'city': 'Regina',
        'province': 'SK',
        'latitude': 50.4452,
        'longitude': -104.5890,
        'location_type': 'truck_stop',
        'total_spots': 90,
        'bobtail_spots': 15,
        'trailer_spots': 60,
        'oversize_spots': 15,
        'lcv_capable': True,
        'daily_rate': 2000,
        'monthly_rate': 35000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "wifi", "restaurant_onsite", "fuel_nearby", "cat_scale", "block_heater_plugin", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    {
        'name': 'Husky Travel Centre Saskatoon',
        'address': '3155 Idylwyld Dr N',
        'city': 'Saskatoon',
        'province': 'SK',
        'latitude': 52.1579,
        'longitude': -106.6702,
        'location_type': 'truck_stop',
        'total_spots': 60,
        'bobtail_spots': 10,
        'trailer_spots': 40,
        'oversize_spots': 10,
        'daily_rate': 1800,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 11", "Hwy 16"],
    },
    {
        'name': 'Moose Jaw Truck Stop',
        'address': '330 Thatcher Dr E',
        'city': 'Moose Jaw',
        'province': 'SK',
        'latitude': 50.3929,
        'longitude': -105.5225,
        'location_type': 'truck_stop',
        'total_spots': 35,
        'bobtail_spots': 5,
        'trailer_spots': 25,
        'oversize_spots': 5,
        'lcv_capable': True,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 1", "Hwy 2"],
    },
    {
        'name': 'Swift Current Rest Area',
        'address': 'Trans-Canada Hwy 1',
        'city': 'Swift Current',
        'province': 'SK',
        'latitude': 50.2881,
        'longitude': -107.7938,
        'location_type': 'rest_area',
        'total_spots': 25,
        'trailer_spots': 20,
        'oversize_spots': 5,
        'amenities': ["restrooms", "lit_lot", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    # ===== QUEBEC =====
    {
        'name': 'Irving Big Stop Riviere-du-Loup',
        'address': '62 Boulevard Cartier',
        'city': 'Riviere-du-Loup',
        'province': 'QC',
        'latitude': 47.8407,
        'longitude': -69.5200,
        'location_type': 'truck_stop',
        'total_spots': 70,
        'bobtail_spots': 10,
        'trailer_spots': 50,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "restaurant_onsite", "fuel_nearby", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Autoroute 20", "Trans-Canada"],
    },
    {
        'name': 'Ultramar Truck Stop Drummondville',
        'address': '1500 Boulevard Saint-Joseph',
        'city': 'Drummondville',
        'province': 'QC',
        'latitude': 45.8834,
        'longitude': -72.4843,
        'location_type': 'truck_stop',
        'total_spots': 50,
        'bobtail_spots': 10,
        'trailer_spots': 35,
        'oversize_spots': 5,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "paved"],
        'nearby_highways': ["Autoroute 20", "Autoroute 55"],
    },
    {
        'name': 'Petro-Canada Trois-Rivieres',
        'address': '4400 Boulevard des Forges',
        'city': 'Trois-Rivieres',
        'province': 'QC',
        'latitude': 46.3432,
        'longitude': -72.5413,
        'location_type': 'truck_stop',
        'total_spots': 40,
        'bobtail_spots': 8,
        'trailer_spots': 25,
        'oversize_spots': 7,
        'daily_rate': 1800,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "paved"],
        'nearby_highways': ["Autoroute 40", "Autoroute 55"],
    },
    {
        'name': 'Relais Routier St-Hyacinthe',
        'address': '5200 Boulevard Laurier O',
        'city': 'Saint-Hyacinthe',
        'province': 'QC',
        'latitude': 45.6307,
        'longitude': -72.9571,
        'location_type': 'truck_stop',
        'total_spots': 45,
        'bobtail_spots': 8,
        'trailer_spots': 30,
        'oversize_spots': 7,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "restaurant_onsite", "paved"],
        'nearby_highways': ["Autoroute 20"],
    },
    {
        'name': 'Irving Levis',
        'address': '7350 Boulevard de la Rive-Sud',
        'city': 'Levis',
        'province': 'QC',
        'latitude': 46.7907,
        'longitude': -71.1773,
        'location_type': 'truck_stop',
        'total_spots': 55,
        'bobtail_spots': 10,
        'trailer_spots': 35,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Autoroute 20", "Autoroute 73"],
    },
    {
        'name': 'Boucherville Industrial Parking',
        'address': '1500 Rue Eiffel',
        'city': 'Boucherville',
        'province': 'QC',
        'latitude': 45.5988,
        'longitude': -73.4293,
        'location_type': 'industrial_lot',
        'total_spots': 60,
        'trailer_spots': 45,
        'oversize_spots': 15,
        'daily_rate': 3500,
        'weekly_rate': 17000,
        'monthly_rate': 55000,
        'amenities': ["security_camera", "24_7_access", "fenced", "gated", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Autoroute 20", "Autoroute 30"],
    },
    # ===== NEW BRUNSWICK =====
    {
        'name': 'Irving Big Stop Moncton',
        'address': '1199 Mountain Rd',
        'city': 'Moncton',
        'province': 'NB',
        'latitude': 46.1185,
        'longitude': -64.8019,
        'location_type': 'truck_stop',
        'total_spots': 60,
        'bobtail_spots': 10,
        'trailer_spots': 40,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "restaurant_onsite", "fuel_nearby", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 2"],
    },
    {
        'name': 'Irving Big Stop Fredericton',
        'address': '1171 Prospect St',
        'city': 'Fredericton',
        'province': 'NB',
        'latitude': 45.9636,
        'longitude': -66.6431,
        'location_type': 'truck_stop',
        'total_spots': 45,
        'bobtail_spots': 8,
        'trailer_spots': 30,
        'oversize_spots': 7,
        'daily_rate': 1800,
        'amenities': ["24_7_access", "restrooms", "showers", "restaurant_onsite", "fuel_nearby", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 2"],
    },
    {
        'name': 'Edmundston Rest Area',
        'address': 'Trans-Canada Hwy 2',
        'city': 'Edmundston',
        'province': 'NB',
        'latitude': 47.3737,
        'longitude': -68.3253,
        'location_type': 'rest_area',
        'total_spots': 20,
        'trailer_spots': 15,
        'oversize_spots': 5,
        'amenities': ["restrooms", "lit_lot", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 2"],
    },
    # ===== NOVA SCOTIA =====
    {
        'name': 'Irving Big Stop Enfield',
        'address': '419 Hwy 2',
        'city': 'Enfield',
        'province': 'NS',
        'latitude': 44.9200,
        'longitude': -63.5500,
        'location_type': 'truck_stop',
        'total_spots': 50,
        'bobtail_spots': 8,
        'trailer_spots': 35,
        'oversize_spots': 7,
        'daily_rate': 2000,
        'amenities': ["security_camera", "24_7_access", "restrooms", "showers", "restaurant_onsite", "fuel_nearby", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 102"],
    },
    {
        'name': 'Irving Big Stop Amherst',
        'address': '40 E Victoria St',
        'city': 'Amherst',
        'province': 'NS',
        'latitude': 45.8326,
        'longitude': -64.2131,
        'location_type': 'truck_stop',
        'total_spots': 40,
        'bobtail_spots': 8,
        'trailer_spots': 25,
        'oversize_spots': 7,
        'daily_rate': 1800,
        'amenities': ["24_7_access", "restrooms", "showers", "restaurant_onsite", "fuel_nearby", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 104"],
    },
    {
        'name': 'Truro Truck Stop',
        'address': '437 Robie St',
        'city': 'Truro',
        'province': 'NS',
        'latitude': 45.3653,
        'longitude': -63.2800,
        'location_type': 'truck_stop',
        'total_spots': 30,
        'bobtail_spots': 5,
        'trailer_spots': 20,
        'oversize_spots': 5,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 102", "Hwy 104"],
    },
    # ===== NEWFOUNDLAND & LABRADOR =====
    {
        'name': 'Irving Whitbourne',
        'address': 'Trans-Canada Hwy',
        'city': 'Whitbourne',
        'province': 'NL',
        'latitude': 47.4500,
        'longitude': -53.5300,
        'location_type': 'truck_stop',
        'total_spots': 25,
        'bobtail_spots': 5,
        'trailer_spots': 15,
        'oversize_spots': 5,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    {
        'name': 'North Atlantic Truck Stop',
        'address': '60 Clyde Ave',
        'city': 'Corner Brook',
        'province': 'NL',
        'latitude': 48.9500,
        'longitude': -57.9500,
        'location_type': 'truck_stop',
        'total_spots': 20,
        'bobtail_spots': 5,
        'trailer_spots': 12,
        'oversize_spots': 3,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    # ===== PRINCE EDWARD ISLAND =====
    {
        'name': 'Irving Borden-Carleton',
        'address': '203 Trans-Canada Hwy',
        'city': 'Borden-Carleton',
        'province': 'PE',
        'latitude': 46.2515,
        'longitude': -63.7068,
        'location_type': 'truck_stop',
        'total_spots': 25,
        'bobtail_spots': 5,
        'trailer_spots': 15,
        'oversize_spots': 5,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "paved"],
        'nearby_highways': ["Trans-Canada"],
    },
    # ===== YUKON =====
    {
        'name': 'Whitehorse Truck Stop',
        'address': '2237 2nd Ave',
        'city': 'Whitehorse',
        'province': 'YT',
        'latitude': 60.7212,
        'longitude': -135.0568,
        'location_type': 'truck_stop',
        'total_spots': 20,
        'bobtail_spots': 5,
        'trailer_spots': 12,
        'oversize_spots': 3,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "gravel"],
        'nearby_highways': ["Alaska Hwy"],
    },
    # ===== NORTHWEST TERRITORIES =====
    {
        'name': 'Yellowknife Truck Parking',
        'address': '4807 49th St',
        'city': 'Yellowknife',
        'province': 'NT',
        'latitude': 62.4540,
        'longitude': -114.3718,
        'location_type': 'industrial_lot',
        'total_spots': 15,
        'bobtail_spots': 5,
        'trailer_spots': 8,
        'oversize_spots': 2,
        'daily_rate': 2500,
        'amenities': ["24_7_access", "block_heater_plugin", "gravel"],
        'nearby_highways': ["Hwy 4"],
    },
    # Additional Ontario locations
    {
        'name': 'Milton ONroute',
        'address': 'Hwy 401 Westbound',
        'city': 'Milton',
        'province': 'ON',
        'latitude': 43.5183,
        'longitude': -79.8828,
        'location_type': 'rest_area',
        'total_spots': 50,
        'trailer_spots': 40,
        'oversize_spots': 10,
        'amenities': ["restrooms", "food_nearby", "restaurant_onsite", "lit_lot", "paved"],
        'nearby_highways': ["Hwy 401"],
    },
    {
        'name': 'Kitchener Truck Yard',
        'address': '1110 King St E',
        'city': 'Kitchener',
        'province': 'ON',
        'latitude': 43.4393,
        'longitude': -80.4604,
        'location_type': 'private_yard',
        'total_spots': 35,
        'trailer_spots': 25,
        'oversize_spots': 10,
        'daily_rate': 2500,
        'weekly_rate': 12000,
        'monthly_rate': 40000,
        'amenities': ["security_camera", "24_7_access", "fenced", "gated", "lit_lot", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 401", "Hwy 8"],
    },
    {
        'name': 'Hamilton Truck Stop',
        'address': '2540 Barton St E',
        'city': 'Hamilton',
        'province': 'ON',
        'latitude': 43.2557,
        'longitude': -79.8033,
        'location_type': 'truck_stop',
        'total_spots': 40,
        'bobtail_spots': 8,
        'trailer_spots': 25,
        'oversize_spots': 7,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "food_nearby", "lit_lot", "paved"],
        'nearby_highways': ["QEW", "Hwy 403"],
    },
    {
        'name': 'Sault Ste Marie Truck Stop',
        'address': '800 Great Northern Rd',
        'city': 'Sault Ste Marie',
        'province': 'ON',
        'latitude': 46.5136,
        'longitude': -84.3358,
        'location_type': 'truck_stop',
        'total_spots': 30,
        'bobtail_spots': 5,
        'trailer_spots': 20,
        'oversize_spots': 5,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Trans-Canada", "Hwy 17"],
    },
    {
        'name': 'Sudbury Rest Stop',
        'address': 'Trans-Canada Hwy 17',
        'city': 'Sudbury',
        'province': 'ON',
        'latitude': 46.4917,
        'longitude': -81.0000,
        'location_type': 'rest_area',
        'total_spots': 25,
        'trailer_spots': 20,
        'oversize_spots': 5,
        'amenities': ["restrooms", "lit_lot", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 17"],
    },
    # Additional Quebec locations
    {
        'name': 'Ultramar Montreal-Est',
        'address': '11500 Rue Sherbrooke E',
        'city': 'Montreal-Est',
        'province': 'QC',
        'latitude': 45.6300,
        'longitude': -73.5100,
        'location_type': 'truck_stop',
        'total_spots': 45,
        'bobtail_spots': 8,
        'trailer_spots': 30,
        'oversize_spots': 7,
        'daily_rate': 2500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "paved"],
        'nearby_highways': ["Autoroute 40", "Autoroute 25"],
    },
    {
        'name': 'Relais Routier Quebec City',
        'address': '3500 Boulevard Wilfrid-Hamel',
        'city': 'Quebec City',
        'province': 'QC',
        'latitude': 46.8139,
        'longitude': -71.2893,
        'location_type': 'truck_stop',
        'total_spots': 50,
        'bobtail_spots': 10,
        'trailer_spots': 30,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "restaurant_onsite", "paved", "snow_removal"],
        'nearby_highways': ["Autoroute 40", "Autoroute 73"],
    },
    # Additional Alberta
    {
        'name': 'Grande Prairie Truck Stop',
        'address': '11101 100 Ave',
        'city': 'Grande Prairie',
        'province': 'AB',
        'latitude': 55.1707,
        'longitude': -118.7947,
        'location_type': 'truck_stop',
        'total_spots': 50,
        'bobtail_spots': 10,
        'trailer_spots': 30,
        'oversize_spots': 10,
        'daily_rate': 2000,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 43", "Hwy 2"],
    },
    {
        'name': 'Fort McMurray Truck Terminal',
        'address': '201 Gregoire Dr',
        'city': 'Fort McMurray',
        'province': 'AB',
        'latitude': 56.7267,
        'longitude': -111.3803,
        'location_type': 'industrial_lot',
        'total_spots': 80,
        'trailer_spots': 50,
        'oversize_spots': 30,
        'daily_rate': 3500,
        'weekly_rate': 18000,
        'monthly_rate': 60000,
        'amenities': ["security_camera", "24_7_access", "fenced", "gated", "block_heater_plugin", "lit_lot", "gravel", "snow_removal"],
        'nearby_highways': ["Hwy 63"],
    },
    # Additional Manitoba
    {
        'name': 'Steinbach Truck Stop',
        'address': '300 Brandt St',
        'city': 'Steinbach',
        'province': 'MB',
        'latitude': 49.5258,
        'longitude': -96.6839,
        'location_type': 'truck_stop',
        'total_spots': 30,
        'bobtail_spots': 5,
        'trailer_spots': 20,
        'oversize_spots': 5,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 12", "Hwy 52"],
    },
    {
        'name': 'Emerson Border Truck Parking',
        'address': 'Hwy 75',
        'city': 'Emerson',
        'province': 'MB',
        'latitude': 49.0095,
        'longitude': -97.2137,
        'location_type': 'private_yard',
        'total_spots': 30,
        'trailer_spots': 25,
        'oversize_spots': 5,
        'daily_rate': 2000,
        'amenities': ["security_camera", "24_7_access", "fenced", "lit_lot", "gravel"],
        'nearby_highways': ["Hwy 75", "I-29"],
    },
    # Additional BC
    {
        'name': 'Chilliwack Truck Stop',
        'address': '45835 Yale Rd W',
        'city': 'Chilliwack',
        'province': 'BC',
        'latitude': 49.1579,
        'longitude': -121.9514,
        'location_type': 'truck_stop',
        'total_spots': 40,
        'bobtail_spots': 8,
        'trailer_spots': 25,
        'oversize_spots': 7,
        'daily_rate': 2500,
        'amenities': ["24_7_access", "restrooms", "showers", "fuel_nearby", "food_nearby", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 1"],
    },
    {
        'name': 'Cache Creek Rest Area',
        'address': 'Trans-Canada Hwy 1',
        'city': 'Cache Creek',
        'province': 'BC',
        'latitude': 50.8100,
        'longitude': -121.3200,
        'location_type': 'rest_area',
        'total_spots': 20,
        'trailer_spots': 15,
        'oversize_spots': 5,
        'amenities': ["restrooms", "paved"],
        'nearby_highways': ["Trans-Canada", "Hwy 1", "Hwy 97"],
    },
    # Additional Saskatchewan
    {
        'name': 'North Battleford Truck Stop',
        'address': '11402 Railway Ave E',
        'city': 'North Battleford',
        'province': 'SK',
        'latitude': 52.7575,
        'longitude': -108.2861,
        'location_type': 'truck_stop',
        'total_spots': 30,
        'bobtail_spots': 5,
        'trailer_spots': 20,
        'oversize_spots': 5,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "paved", "snow_removal"],
        'nearby_highways': ["Hwy 16", "Hwy 40"],
    },
    {
        'name': 'Prince Albert Truck Terminal',
        'address': '99 Marquis Rd E',
        'city': 'Prince Albert',
        'province': 'SK',
        'latitude': 53.2033,
        'longitude': -105.7531,
        'location_type': 'truck_stop',
        'total_spots': 25,
        'bobtail_spots': 5,
        'trailer_spots': 15,
        'oversize_spots': 5,
        'daily_rate': 1500,
        'amenities': ["24_7_access", "restrooms", "fuel_nearby", "block_heater_plugin", "paved"],
        'nearby_highways': ["Hwy 2", "Hwy 11"],
    },
]


def seed_locations():
    """Insert seed locations if the table is empty."""
    if ParkingLocation.query.first():
        logger.info("Locations already seeded, skipping")
        return
    for loc_data in SEED_LOCATIONS:
        slug = slugify(f"{loc_data['name']}-{loc_data['city']}")
        existing = ParkingLocation.query.filter_by(slug=slug).first()
        if existing:
            continue
        loc = ParkingLocation(
            name=loc_data['name'],
            slug=slug,
            address=loc_data['address'],
            city=loc_data['city'],
            province=loc_data['province'],
            latitude=loc_data['latitude'],
            longitude=loc_data['longitude'],
            location_type=loc_data.get('location_type', 'truck_stop'),
            total_spots=loc_data.get('total_spots', 0),
            bobtail_spots=loc_data.get('bobtail_spots', 0),
            trailer_spots=loc_data.get('trailer_spots', 0),
            oversize_spots=loc_data.get('oversize_spots', 0),
            lcv_capable=loc_data.get('lcv_capable', False),
            hourly_rate=loc_data.get('hourly_rate'),
            daily_rate=loc_data.get('daily_rate'),
            weekly_rate=loc_data.get('weekly_rate'),
            monthly_rate=loc_data.get('monthly_rate'),
            amenities=loc_data.get('amenities', []),
            nearby_highways=loc_data.get('nearby_highways', []),
            is_active=True,
        )
        db.session.add(loc)
    db.session.commit()
    logger.info("Seeded %d parking locations", len(SEED_LOCATIONS))
